# Generated by Django 5.2.6 on 2025-09-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
