# Generated by Django 5.2.6 on 2025-10-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
